Update README.md
Dennci/CPPT_KERNYCHNYI_DI_39_1 pull request #1
Opened 2023-03-12 03:05 UTC by Dennci

Курсова робота з предмету: "Системне програмне забезпечення"

Я обрав тему (13)Розробка програмного забезпечення для моніторингу подій на комп'ютері. Розробка програми, що моніторить події, що відбуваються на комп'ютері та зберігає історію їх виконання.

Для себе я відокремив такі пунки для виконання системи:

Програма повинна моніторити всі події, які робить юзер на комп'ютері: такі як відкриття файлів, запуск/закривання програм, введення тексту, тощо.
Історія подій має зберігатись у форматі txt.

2023-03-13 21:26 UTC, NULP-KI requested changes
1. Не видаляй опис
2. Події мають зберігатися у форматі xml, json, або yaml щоб їх було легше обробляти комп'ютером.
3. Продумай уважно який функціонал має бути і напиши в деталях.

2023-03-14 21:34 UTC, NULP-KI commented
Внеси деталізований опис з коментаря у readme.md

2023-03-15 14:17 UTC, Dennci commented
> Внеси деталізований опис з коментаря у readme.md

Так він є занесеним у Readme

2023-03-22 21:16 UTC, NULP-KI commented
тоді закрий пул реквест, бо він збиває з пантелику.

2023-04-11 20:35 UTC, merged